spring:
  datasource:
    url: jdbc:postgresql://db:5432/react_spring_playground
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true